title: ResearchWaste.info
author: "Pavel Zhelnov"
author_pronouns: "he/him"
email: p.zhelnov@mail.utoronto.ca
description: >- # this means to ignore newlines until "baseurl:"
  AWARE is a doctoral research project in progress at the University
  of Toronto and the SPOR Evidence Alliance focused on reducing
  research waste in health and biomedical sciences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://researchwaste.info" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:   drzhelnov
github_username:    drzhelnov
github_repo:        aware
linkedin_username:  drzhelnov
#instagram_username: the_trash_scientist
bluesky_username:   researchwaste.info
comment_landing_url: https://docs.google.com/document/d/1kHBxe7XmJcfp8T32QxAjJqqPs_LRu4EIM4cpa_GWT7E/edit
latest_doc_url:      https://docs.google.com/document/d/1kHBxe7XmJcfp8T32QxAjJqqPs_LRu4EIM4cpa_GWT7E/edit
cta_button: "<a href=\"https://docs.google.com/document/d/1kHBxe7XmJcfp8T32QxAjJqqPs_LRu4EIM4cpa_GWT7E/edit\" class=\"cta-button\" target=\"_blank\" rel=\"noopener noreferrer\">Comment on Latest Paper</a>"

# Layout defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "README.md"
    values:
      layout: "landing"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-target-blank

# Readme Index settings
readme_index:
  enabled:          false
  remove_originals: true
  with_frontmatter: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - untracked/
  - LICENSE
  - dev/
  - netlify/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
include:
  - LICENSE_MINIMA

google_analytics: G-KLYY520MTK
