title: Research Waste AWARE
author: "Pavel Zhelnov, MD"
email: p.zhelnov@mail.utoronto.ca
description: >- # this means to ignore newlines until "baseurl:"
  AWARE is a scoping review of Avoidable WAste in REsearch and
  a tool in development to inform academics, clinicians, patient
  and public partners, policy-makers, and funders on how to reduce
  research waste in health and biomedical sciences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://researchwaste.info" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: drzhelnov
github_username:  pvzhelnov

# Layout defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "README.md"
    values:
      layout: "landing"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-optional-front-matter
  - jekyll-target-blank

# Readme Index settings
readme_index:
  enabled:          false
  remove_originals: true
  with_frontmatter: false

# Optional Front Matter settings
optional_front_matter:
  enabled:          true
  remove_originals: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - untracked/
  - LICENSE
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
include:
  - LICENSE_MINIMA
